accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('cadastro/', views.register_view, name='cadastro'),
    path('login/', views.login_view, name='login'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('traders.urls')),
    path('', include('accounts.urls')),
]

traders/urls.py
from django.urls import path
from traders import views

app_name = 'traders'

urlpatterns = [
    path('', views.home, name='home'),
    path('sala/', views.link_sala, name='link_sala'),
    path('plataforma/', views.plataforma, name='plataforma'),
]

accounts/models.py
from django.db import models

# Create your models here.

traders/models.py
from django.db import models


class Traders(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=80)
    celular = models.CharField(max_length=15)
    email = models.CharField(max_length=150)

traders/forms.py
from django import forms
from traders.models import Traders


class TradersModelForm(forms.ModelForm):

    class Meta:
        model = Traders
        fields = '__all__'

accounts/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect


def register_view(request):
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect("accounts:login")
    else:
        user_form = UserCreationForm()
    return render(request, 'pages/cadastro.html', {"user_form": user_form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('traders:home')
        else:
            login_form = AuthenticationForm()
    else:
        login_form = AuthenticationForm()
    return render(request, 'pages/login.html', {'login_form': login_form})

traders/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def home(request):
    return render(request, 'pages/home.html')


@method_decorator(login_required(login_url='accounts:login'), name="dispatch")
def link_sala(request):
    return render(request, 'pages/link_sala.html')


def plataforma(request):
    return render(request, 'pages/plataforma.html')

accounts/templates/accounts/pages/cadastro.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}

    <div class="form-group">
      {{ user_form.username.errors }}
      <label>Usuário:</label>
      {{ user_form.username }}
    </div>
    <div class="form-group">
      {{ user_form.password.errors }}
      <label>Senha:</label>
      {{ user_form.password1 }}
    </div>
    <div class="form-group">
      {{ user_form.password2.errors }}
      <label>Confirme Senha:</label>
      {{ user_form.password2 }}
    </div>
    <div class="form-group">
      <input type="submit" value="Cadastrar">
    </div>

  </form>
{% endblock %}

accounts/templates/accounts/pages/login.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>
      {{ login_form.as_table }}
    </table>

    <input type="submit" value="Login">
  </form>
{% endblock %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'traders/css/styles.css' %}">
    <title>Bot Cripto Trader</title>
</head>
<body>
    {% include 'partials/header.html' %}

    <div class="main-content-container" >
        {% block content %} {% endblock %}
    </div>

    {% include 'partials/footer.html' %}
</body>
</html>

traders/templates/traders/pages/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="main-content">
        <div class="main-title">
            <h1>Olá, {{user.username}}</h1>
        </div>
        <div class="poster-logo">
            <img src="">
        </div>
        <div class="options-group">
            <ul>
                <li><a href="{% url 'traders:plataforma' %}">Plataforma</a></li>
                <li><a href="{% url 'traders:link_sala' %}">Link Ativação</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:cadastro' %}">Cadastro</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

traders/templates/traders/pages/link_sala.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

traders/templates/traders/pages/plataforma.html
{% extends 'base.html' %}

{% block content %}

<div class="main-content content">
    <div class="main-title">
        <h1>Plataforma de Sinas</h1>
    </div>
    <div class="tabela-sinais">
        <table>

        </table>
    </div>
</div>

{% endblock %}

traders/templates/traders/partials/footer.html
<footer class="main-footer">
    <p>Bot Crypto Trader 2024</p>
</footer>

traders/templates/traders/partials/head.html
{% load static %}

traders/templates/traders/partials/header.html
    <header class="main-header-container">
        <div class="main-header container">
            <h1 >
                <a class="main-logo" href="{% url 'traders:home' %}">
                    <i class="fa-solid fa-utensils main-logo-icon"></i>
                    <span class="main-logo-text"> Bot Cripto Trader</span>
                </a>
            </h1>
        </div>
    </header>